"""empty message

Revision ID: 42d64584b4b6
Revises: dacea8dbc7df
Create Date: 2025-11-20 15:27:00.082400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42d64584b4b6'
down_revision = 'dacea8dbc7df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites_starships',
    sa.Column('favorite_id', sa.Integer(), nullable=True),
    sa.Column('starship_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['favorite_id'], ['favorites.id'], ),
    sa.ForeignKeyConstraint(['starship_id'], ['starships.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites_starships')
    # ### end Alembic commands ###
