"""empty message

Revision ID: 934813a1f6e4
Revises: d73fae32c319
Create Date: 2025-11-22 10:29:04.841215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '934813a1f6e4'
down_revision = 'd73fae32c319'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_column('starships.id')
        batch_op.drop_column('characters.id')
        batch_op.drop_column('planets.id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planets.id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('characters.id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('starships.id', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
